services:
  valkey:
    image: valkey/valkey:latest
#    container_name: valkey_instance
    ports:
      - "6379:6379"
#    environment:
#      - VALKEY_CONFIG=/config/valkey.yaml
#    volumes:
#      - ./config:/config
