package com.lzag.ratelimiter

enum class RateLimiterAlgo {
  TOKEN_BUCKET,
  LEAKY_BUCKET,
  TIMESTAMP_BUCKET,
  SLIDING_WINDOW_LOG,
  SLIDING_WINDOW_COUNTER,
  FIXED_WINDOW_COUNTER,
  FIXED_WINDOW_COUNTER_AND_CONCURRENT
}
